apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hayden-portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haydumb/hayden-portfolio
    targetRevision: main
    path: infra/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: hayden-portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
